### ISSUE TITLE
Should "can be queued" be "can be queried"?

### ISSUE THREAD

**Issue by shlomif** [wernerkrauss/awesome-silverstripe#18]
In https://github.com/wernerkrauss/awesome-silverstripe there is this text:

> It is a rapid development MVC framework that serves as a classic fully fledged CMS or as a headless CMS, which can be queued either via GraphQL or a custom API.

I suspect you meant [queried](https://en.wiktionary.org/wiki/query) rather than [queued](https://en.wiktionary.org/wiki/queue). Thanks!

**Comment by wernerkrauss** [comment]
Absolutely. Good catch. Do you want to PR it for hacktoberfest or should I fix it?

**Comment by shlomif** [comment]
> Absolutely. Good catch. Do you want to PR it for hacktoberfest or should I fix it?

I'm not taking part in hacktoberfest this year as a submitter of pull reqs (only as a recipient of them), so feel free to fix it. Thanks for the thought though.
