### ISSUE TITLE
Submit sindresorhus/awesome

### ISSUE THREAD

**Issue by wernerkrauss** [wernerkrauss/awesome-silverstripe#2]
when it has matured a bit.

See https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

- [x] rename master to main
- [x] fix linting errors
- [x] add succinct description
- [x] add high-res logo (if possible)
- [x] check outdated projects, low quality projects (e.g. no docs) etc...
- [x] all entries have a description
- [x] licence in seperate file
- [x] contribution guidelines

**Comment by wernerkrauss** [comment]
See https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md for what's to be done until a successful PR can be made

**Comment by sunnysideup** [comment]
+1

**Comment by Firesphere** [comment]
A few things needs to change to make it compatible with awesome, it seems, including renaming the `master` branch to `main`

**Comment by wernerkrauss** [comment]
And it's finally commited: https://github.com/sindresorhus/awesome/pull/1879

**Comment by wernerkrauss** [comment]
Officially listed since 10.01.2021
