### ISSUE TITLE
adding another link: http://ssmods.com/

### ISSUE THREAD

**Issue by sunnysideup** [wernerkrauss/awesome-silverstripe#4]
Hi 

Would you mind adding http://ssmods.com/ as a link here?  If you are not keen then let me know what it would take to get it listed ;-)

Thank you so much

Greetings from Wellington

Nicolaas

**Comment by wernerkrauss** [comment]
Hi Nicolaas,

sure, please provide a PR for it with a description. From what I see it's "just another maybe better or more fancy module listing" ??
